version: '3.8'

services:
  cloudy_coffee_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudy_coffee_app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - cloudy_coffee_database
    networks:
      -
        cloudy_coffee
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  cloudy_coffee_database:
    image: mongo:latest
    container_name: cloudy_coffee_database
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: nestjs
    volumes:
      - cloudy_coffee_database:/data/db
    networks:
      - cloudy_coffee

  cloudy_coffee_minio:
    image: minio/minio:latest
    container_name: cloudy_coffee_minio
    ports:
      - "9000:9000" # MinIO API port
      - "9001:9001" # MinIO Console port
    environment:
      MINIO_ROOT_USER: minioadmin # Default username
      MINIO_ROOT_PASSWORD: minioadmin # Default password
    command: server /data --console-address ":9001"
    volumes:
      - cloudy_coffee_minio:/data
    networks:
      - cloudy_coffee

volumes:
  cloudy_coffee_database:
  cloudy_coffee_minio:
  node_modules:

networks:
  cloudy_coffee:
    driver: bridge
